title: [El librito de Anselmo]
description: [Apuntes variados que seguro alguno te va a servir 😉]
remote_theme: pages-themes/architect@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
